# Generated by Django 4.2.7 on 2023-11-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="название")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="название")),
                (
                    "music_file",
                    models.FileField(
                        upload_to="music/", verbose_name="музыкальный файл"
                    ),
                ),
                (
                    "music_image",
                    models.ImageField(
                        upload_to="images/music/",
                        verbose_name="обложка музыкального файла",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music",
                        to="users_music.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "музыка",
                "verbose_name_plural": "музыка",
            },
        ),
    ]
