# Generated by Django 4.2.7 on 2023-11-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Albom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
            ],
            options={
                "verbose_name": "альбом",
                "verbose_name_plural": "альбомы",
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
            ],
            options={
                "verbose_name": "артист",
                "verbose_name_plural": "артисты",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название"
                    ),
                ),
                (
                    "music_file",
                    models.FileField(
                        upload_to="music/", verbose_name="музыкальный файл"
                    ),
                ),
                (
                    "music_image",
                    models.ImageField(
                        default="default/default_music_image.png",
                        upload_to="images/music/",
                        verbose_name="обложка музыкального файла",
                    ),
                ),
                (
                    "albom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music",
                        to="users_music.albom",
                        verbose_name="альбом",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music",
                        to="users_music.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "музыка",
                "verbose_name_plural": "музыка",
            },
        ),
        migrations.AddField(
            model_name="albom",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="music",
                to="users_music.artist",
                verbose_name="исполнитель",
            ),
        ),
    ]
