# Generated by Django 4.2.5 on 2023-11-26 07:20

import django.core.validators
from django.db import migrations, models
import users_music.models


class Migration(migrations.Migration):
    dependencies = [
        ("users_music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="music_file",
            field=models.FileField(
                upload_to=users_music.models.Music._image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "wav", "ogg"]
                    )
                ],
                verbose_name="музыкальный файл",
            ),
        ),
    ]
