# Generated by Django 4.2.7 on 2023-11-21 16:52

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users_music", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNewFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default/default_user_image.png/",
                        null=True,
                        upload_to="images/users/",
                        verbose_name="аватарка",
                    ),
                ),
                (
                    "music",
                    models.ManyToManyField(
                        blank=True,
                        related_name="added_fields",
                        to="users_music.music",
                        verbose_name="музыка",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_fields",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "дополнительное поле",
                "verbose_name_plural": "дополнительные поля",
            },
            bases=(models.Model, core.models.ImageOperations),
        ),
    ]
