# Generated by Django 4.2.7 on 2023-11-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernewfields",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default/default_user_image.png",
                null=True,
                upload_to="images/users/",
                verbose_name="аватарка",
            ),
        ),
    ]
