# Generated by Django 4.2.5 on 2023-11-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_music", "0001_initial"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rooms",
            name="user",
        ),
        migrations.AddField(
            model_name="usersrooms",
            name="is_admin",
            field=models.BooleanField(
                default=False, verbose_name="является ли администратором"
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="current",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="users_music.music",
                verbose_name="музыка",
            ),
        ),
    ]
